### ISSUE TITLE
Usage on Linux

### ISSUE THREAD

**Issue by gdhgdhgdh** [nabezokodaikon/pcars2-telemetry-browsing#2]
Hello!

What a super-looking project - I'm trying to run it on Ubuntu 16.04, and whilst the Mac launch shell script works fine once I input my LAN IP in `application.conf`, and I can see the web browser OK, I don't get any timing / engine data.

When I set 'debug = true' in the `application.conf`, I get the following Java error trace:

```
21:59 $ sudo bash start-for-mac.sh 
 ____   ____                 ____  
|  _ \ / ___|__ _ _ __ ___  |___ \ 
| |_) | |   / _` | '__/ __|   __) |
|  __/| |__| (_| | |  \__ \  / __/ 
|_|    \____\__,_|_|  |___/ |_____|

Please access 'http://10.0.0.129:9000' on the Web browser.
[ERROR] [01/09/2019 21:59:52.979] [pcars2-telemetry-browsing-akka.actor.default-dispatcher-2] [akka://pcars2-telemetry-browsing/user/udpSender] null
akka.actor.ActorInitializationException: akka://pcars2-telemetry-browsing/user/udpSender: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
	at akka.actor.ActorCell.create(ActorCell.scala:608)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
	... 9 more
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:197)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:197)
	at scala.collection.SeqLike.size(SeqLike.scala:105)
	at scala.collection.SeqLike.size$(SeqLike.scala:105)
	at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:191)
	at scala.collection.IndexedSeqLike.sizeHintIfCheap(IndexedSeqLike.scala:96)
	at scala.collection.IndexedSeqLike.sizeHintIfCheap$(IndexedSeqLike.scala:96)
	at scala.collection.mutable.ArrayOps$ofRef.sizeHintIfCheap(ArrayOps.scala:191)
	at scala.collection.mutable.Builder.sizeHint(Builder.scala:77)
	at scala.collection.mutable.Builder.sizeHint$(Builder.scala:76)
	at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:21)
	at scala.collection.TraversableLike.builder$1(TraversableLike.scala:230)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:191)
	at pcars2tb.example.udp.UdpTestDataSender.<init>(UdpTestDataSender.scala:41)
	... 18 more
```

Is there something I can do to help debug this? When I use `tcpdump` I can see the Xbox sending tons of UDP data to 255.255.255.255 on port 5606, so it doesn't look to be a network problem.

**Comment by nabezokodaikon** [comment]
Sorry. This application development is closed.
